{
    "location_street_label": "Straat",
    "location_street_description": "Geef de straat in.",
    "location_zip_label": "Postcode",
    "location_zip_description": "Geef de Postcode in.",
    "location_city_label": "Stad",
    "location_city_description": "Geef de stad in.",
    "location_country_label": "Land",
    "location_country_description": "Geef het land in.",
    "location_map_label": "Kaart",
    "location_map_description": "Selecteer de locatie op de kaart.",
    "location_map_search_headline": "Zoek de locatie op Google Maps",
    "location_map_search_button": "Zoeken",

    "calendar_gcal_label": "Google Kalender",
    "calendar_gcal_description": "Gebruik maken van een Google Agenda-feed?",
    "calendar_hide_label": "Verbergen?",
    "calendar_hide_description": "Moet de kalender aan de frontend getoond worden?",
    "calendar_feedurl_label": "Google Kalender Feed Url",
    "calendar_feedurl_description": "Voer de ID van de kalender die moet worden weergegeven.",
    "calendar_api_key_label": "Google Kalender API Key",
    "calendar_api_key_description": "Geef de Google Kalender API Key in.",
    "calendar_color_label": "Achtergrondkleur",
    "calendar_color_description": "De achtergrondkleur gebruiken de kalender voor de evenementent.",
    "calendar_textcolor_label": "Tekstkleur",
    "calendar_textcolor_description": "De tekst kleur van de kalender gebruikt voor de evenementen.",
    "calendar_viewmode_label": "uitzicht",
    "calendar_viewmode_description": "Hoe moet de kalender eruit zien? (Alleen relevant als de kalender ook effectief getoond wordt)",
    "calendar_viewmode_month": "Maand",
    "calendar_viewmode_week": "Week",
    "calendar_viewmode_day": "Dag",

    "event_start_label": "Startdatum / -tijd",
    "event_start_description": "Dag + Uur waarop het event begint.",
    "event_end_label": "Einddatum / -tijd",
    "event_end_description": "Dag + Uur waarop het event eindigt.",
    "event_allday_label": "Volledige dag",
    "event_allday_description": "Duurt het event de hele dag?",
    "event_location_label": "Locatie",
    "event_location_description": "Locatie van het event.",
    "event_categories_label": "Categorie",
    "event_categories_description": "Onder welke categorie valt het event",
    "event_weekday_label": "Weekdag",
    "event_weekday_description": "Op welke weekdag vindt het event plaats?",
    "event_frequency_label": "Frequentie",
    "event_frequency_description": "Hoe vaak wordt het event herhaald?",
    "event_monthly_label": "Maandelijkse interval",
    "event_monthly_description": "Maandelijkse interval. (Alleen relevant wanneer de frequentie op 'Maandelijks' staat)",
     "event_organiser_label": "Organisator",
    "event_organiser_description": "Wie organiseert het event?",
    "revent_start_label": "Aanvangsuur",
    "revent_start_description": "Uur waarop het event begint.",
    "revent_end_label": "Einduur",
    "revent_end_description": "Uur waarop het event begint.",

    "user_createcalendar_label": "Kalender herstellen",
    "user_createcalendar_description": "Kann der Benutzer Kalender erstellen?",
    "user_deletecalendar_label": "Kalender löschen",
    "user_deletecalendar_description": "Kann der Benutzer Kalender löschen?",
    "user_createlocations_label": "Orte erstellen",
    "user_createlocations_description": "Kann der Benutzer Orte erstellen?",
    "user_deletelocations_label": "Orte löschen",
    "user_deletelocations_description": "Kann der Benutzer Orte löschen?",
    "user_createevents_label": "Events erstellen",
    "user_createevents_description": "Kann der Benutzer Events erstellen?",
    "user_deleteevents_label": "Events löschen",
    "user_deleteevents_description": "Kann der Benutzer Events löschen?",
    "user_calendar_label": "Erlaubte Kalender",
    "user_calendar_description": "Zu welchen Kalendern hat der Benutzer Zugriff?",
    "user_location_label": "Erlaubte Orte",
    "user_location_description": "Zu welchen Orten hat der Benutzer Zugriff?",

    "import_file_label": "Datei",
    "import_file_description": "Die Datei im ics Fomrat die den Kalender und die Events beinhaltet.",
    "import_calendar_label": "Kalender auswählen",
    "import_calendar_description": "Vorhanden Kalender zum importieren wählen oder einen neuen Kalender erstellen."
}